### ISSUE TITLE
PlotSquared v6 support

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/CS-CoreLib2#193]
## Description (Required)

The PlotSquared updated to the v6 version. The CS-CoreLib2 not support the new PlotSquared version.

## Steps to reproduce the Issue (Required)

1. Install the Slimefun and the PlotSquared v6 plugins to the server.

## Expected behavior (Required)

 The CS-CoreLib2 support the new PlotSquared version.

## Server Log / Error Report

https://pastebin.com/Z8YtvNfR

## Server specs (Required)

 - Server Software: Paper
 - Minecraft Version: 1.17

## FULL plugins list (Required)

`Plugins (97): Admin-Chat, AntiArmorStandStack, antiRedstoneClock, ArmorStandEditor, AutoMessage, BetterGUI, BungeeHelpop, BuntetesLogolo, BuycraftX, ChatControlRed, ChestShop, ChestSort, Citizens, CMILib, CombatLogX, CommandHook, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, DyedBackpacks, DynaTech, EcoPower, EnderContainers, EntityDetection, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExtraGear, ExtraTools, FarmLimiter, FluffyMachines, FoxyMachines, GPAccruals, GriefPrevention, GriefPreventionFlags, HeadDatabase, HolographicDisplays, HonapStaffja, Jatekido, Kezdes, LiteXpansion, LockettePro, Lottery, LuckPerms, mcMMO, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, NashornPlus, NoCheatPlus, OpenInv, PlaceholderAPI, PlayerWarps, PlotSquared, PlugMan, PomaBot, PomaDrops, PomaExpansion, PotionArmors, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, SFCalc, Shopkeepers, ShulkerPacks, SirBlobmanCore (SirBlobmanAPI, XSeries), sleep-most, Slimefun, SlimefunFix, SlimefunLuckyBlocks, StaffChat, SurvivalInvisiframes, SzulinapiKalapok, TAB, TokenManager, TokenShopEditor, TokenStaff, TreasureChest, Vault, Votifier, VotingPlugin, WDLCompanion, WDLCompanionGriefPreventionSupport, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags`

**Comment by ErythroCraft** [comment]
[12:34:47] [Server thread/ERROR]: [CS-CoreLib2] An Error occured while querying the Protection Module: "PlotSquared v6.0.1-Premium"
java.lang.NoSuchMethodError: 'void com.plotsquared.core.location.Location.<init>(java.lang.String, int, int, int)'
        at me.mrCookieSlime.Slimefun.cscorelib2.protection.modules.PlotSquared5ProtectionModule.hasPermission(PlotSquared5ProtectionModule.java:39) ~[?:?]
        at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:181) ~[?:?]
        at io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.onInteract(PlantsListener.java:361) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:499) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:485) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot.jar:dev-Spigot-f773da8-f81f499]
        at java.lang.Thread.run(Thread.java:831) [?:?]
