### ISSUE TITLE
PlotSquared v5 not work with this plugin. Need to update this dependency.

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/CS-CoreLib2#64]
```
[22:22:29] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Slimefun vDEV - 484 (git a6a06158)
java.lang.NoClassDefFoundError: com/github/intellectualsites/plotsquared/plot/object/Location
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.modules.PlotSquaredProtectionModule.hasPermission(PlotSquaredProtectionModule.java:31) ~[?:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:192) ~[?:?]
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AGenerator$1.canOpen(AGenerator.java:54) ~[?:?]
	at me.mrCookieSlime.Slimefun.api.inventory.DirtyChestMenu.canOpen(DirtyChestMenu.java:44) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemListener.onRightClick(SlimefunItemListener.java:97) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor238.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-183]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:450) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1052) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1022) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:945) ~[patched_1.15.2.jar:git-Paper-183]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.github.intellectualsites.plotsquared.plot.object.Location
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-183]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 26 more
```

 - Minecraft Version: 1.15.2
 - Slimefun Version: vDEV - 484 (git a6a06158)
 - CS-CoreLib Version: vDEV - 83 (git 8081bb4f)

**Comment by andris155** [comment]
This changes don't fixed this error.

**Comment by TheBusyBiscuit** [comment]
There hasn't even been an update for that...
Learn to be patient.
