### ISSUE TITLE
Slimefun Elemental Staff - Storm error, when use other player Griefprevention claim

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/CS-CoreLib2#98]
## Description (Required)

Slimefun Elemental Staff - Storm error, when use other player Griefprevention claim.

## Steps to reproduce the Issue (Required)

1. Give Elemental Staff - Storm.
2. Use Elemental Staff - Storm on other player claim.

https://www.youtube.com/watch?v=Wj6GpLX5k1k

## Expected behavior (Required)

No write this error and pvp protection work.

## Server Log / Error Report

```
[17:35:56] [Server thread/ERROR]: [CS-CoreLib2] [CS-CoreLib2 - Protection] An Error occured while querying the Protection Module: "GriefPrevention v16.14.0"
java.lang.NullPointerException: null
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.modules.GriefPreventionProtectionModule.hasPermission(GriefPreventionProtectionModule.java:47) ~[?:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:191) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.magical.StormStaff.lambda$getItemHandler$0(StormStaff.java:70) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemListener.lambda$rightClickItem$0(SlimefunItemListener.java:72) ~[?:?]
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.callItemHandler(SlimefunItem.java:788) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemListener.rightClickItem(SlimefunItemListener.java:72) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemListener.onRightClick(SlimefunItemListener.java:50) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor423.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-127]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-127]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-127]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-127]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[patched_1.16.1.jar:git-Paper-127]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:465) ~[patched_1.16.1.jar:git-Paper-127]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:461) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1505) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-127]
	at java.lang.Thread.run(Unknown Source) [?:?
```

## Server specs (Required)

 - Server Software: Paper
 - Minecraft Version: 1.16.1

## FULL plugins list (Required)

Plugins (14): CS-CoreLib, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, LuckPerms, mcMMO, Multiverse-Core, PlugMan, ProtocolLib, Slimefun, Vault, WorldEdit, WorldGuard

**Comment by andris155** [comment]
Thanks
